version: '3.7'

networks:
  develop:

services:
  nginx:
    image: "nginx:alpine"
    ports:
      - "${NGINX_PORT}:80"
    volumes:
      - ./www:/www # 项目目录
      - ./services/nginx/nginx.conf:/etc/nginx/nginx.conf # nginx配置
      - ./services/nginx/sites:/etc/nginx/conf.d # 站点配置
      - ./services/logs/nginx:/var/log/nginx # 日志
    networks:
      - develop
    depends_on:
      - php72
      - mysql
      - redis

  php72:
    build:
      context: ./services/php
      target: php72
    volumes:
      - ./www:/www # 项目目录
      - ./services/php/php.ini:/usr/local/etc/php/php.ini # php配置
      - ./services/logs/php:/var/log/error.log # php错误日志
    networks:
      - develop

  mysql:
    image: "mysql:5.7"
    ports:
      - "${MYSQL_PORT}:3306"
    volumes:
      - ./services/database/mysql:/etc/mysql # mysql配置
      - ./services/database/mysql/data:/var/lib/mysql # mysql数据
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    networks:
      - develop

  redis:
    image: "redis:5.0.6-alpine"
    command: "redis-server /usr/local/etc/redis/redis.conf --appendonly yes"
    ports:
      - "${REDIS_PORT}:6379"
    volumes:
      - ./services/redis/data:/data # redis数据持久化
      - ./services/redis/redis.conf:/usr/local/etc/redis/redis.conf # redis 配置文件
    networks:
      - develop
  workspace:
    container_name: workspace
    tty: true
    build:
      context: ./services/php
      target: workspace
    volumes:
      - ./www:/www
      - ./services/workspace/composer:/root/.composer
    networks:
      - develop
    